import { api } from "./mockApi.js";

const app = document.querySelector("#app");
const esc = s => String(s ?? "").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const date = iso => new Intl.DateTimeFormat("ko-KR",{month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Seoul"}).format(new Date(iso));
const phase = p => p==="IN_PROGRESS"?["진행 중","live"]:p==="ENDED"?["종료","end"]:["예정","soon"];
const toast = msg => { const el=document.querySelector("#toast"); el.textContent=msg; el.classList.add("show"); setTimeout(()=>el.classList.remove("show"),2200); };
const go = path => { history.pushState({},"",path); render(); scrollTo(0,0); };
const roleName = r => ({STUDENT:"교육생",PROFESSOR:"교수자",ADMIN:"관리자"}[r]);
let data,user,query="";

const header = () => `<header class="topbar"><a class="brand" data-link href="/courses"><span class="brand-mark">L</span><span>Learn<b>ary</b></span></a><div class="top-actions"><button class="icon-btn" aria-label="검색">⌕</button><div class="user-chip"><span class="avatar">${esc(user.name[0])}</span><span class="user-meta"><b>${esc(user.name)}</b><small>${roleName(user.role)}${user.classNumber?` · ${user.classNumber}반`:""}</small></span><button class="icon-btn" id="logout" title="로그아웃">↗</button></div></div></header>`;
const shell = body => `<div class="shell">${header()}<main class="wrap">${body}</main></div>`;
const crumbs = (...items) => `<div class="breadcrumbs"><a data-link href="/courses">과목</a>${items.map((x,i)=>`<span>›</span><span>${esc(x)}</span>`).join("")}</div>`;
const statusBadge = s => `<span class="badge ${s==="OPEN"?"open":"resolved"}"><i class="dot"></i>${s==="OPEN"?"답변을 기다려요":"해결됨"}</span>`;
const author = id => data.users.find(x=>x.id===id);
const course = id => data.courses.find(x=>x.id===Number(id));
const answersFor = id => data.answers.filter(x=>x.questionId===id);

function loginView(){
  app.innerHTML=`<div class="login"><section class="login-visual"><a class="brand"><span class="brand-mark">L</span><span>Learnary</span></a><div class="login-copy"><div class="eyebrow">SKALA KNOWLEDGE COMMONS</div><h1>수업이 끝나도,<br>배움은 이어지도록.</h1><p>반을 넘어 질문하고, 교수자의 설명과 최신 학습자료를 한곳에서 다시 찾아보세요.</p></div><div class="quote">“좋은 질문 하나가 다섯 반의 배움이 됩니다.”</div></section><section class="login-form-wrap"><form class="login-form" id="login-form"><h2>다시 만나 반가워요</h2><p>SKALA 학습 지식 공간에 로그인하세요.</p><div class="field"><label>아이디</label><input name="loginId" autocomplete="username" placeholder="아이디를 입력하세요" required></div><div class="field"><label>비밀번호</label><input name="password" type="password" autocomplete="current-password" placeholder="비밀번호를 입력하세요" required></div><div id="login-error" class="login-error hidden"></div><button class="btn primary" type="submit">로그인</button><div class="demo"><b>DEMO ACCOUNTS · 비밀번호 1234</b><div class="demo-grid">${[["student1","1반 교육생"],["student4","4반 교육생"],["professor","담당 교수자"],["admin","관리자"]].map(x=>`<button type="button" data-demo="${x[0]}"><strong>${x[1]}</strong>${x[0]}</button>`).join("")}</div></div></form></section></div>`;
  document.querySelectorAll("[data-demo]").forEach(b=>b.onclick=()=>{document.querySelector('[name=loginId]').value=b.dataset.demo;document.querySelector('[name=password]').value="1234"});
  document.querySelector("#login-form").onsubmit=async e=>{e.preventDefault(); const btn=e.currentTarget.querySelector("button[type=submit]");btn.disabled=true;btn.textContent="로그인 중…";try{user=await api.login(e.currentTarget.loginId.value,e.currentTarget.password.value);go("/courses")}catch(err){const el=document.querySelector("#login-error");el.textContent=err.message;el.classList.remove("hidden");btn.disabled=false;btn.textContent="로그인"}};
}

function coursesView(){
 const filtered=data.courses.filter(c=>c.title.includes(query)||c.instructors.some(i=>i.includes(query))); const unanswered=data.questions.filter(q=>q.status==="OPEN").length;
 app.innerHTML=shell(`<section class="hero"><div class="hero-main"><div class="eyebrow">오늘의 학습 공간</div><h1>${esc(user.name)}님,<br>어떤 궁금증을 해결해볼까요?</h1><p>5개 반의 질문과 답변이 하나로 모이는 곳. 수업이 끝난 과목도 언제든 다시 탐색할 수 있어요.</p></div><div class="hero-side"><div><span class="badge live"><i class="dot"></i>이번 주 활동</span><h3 style="margin-top:14px">함께 쌓은 지식</h3></div><div class="stat-big">${data.answers.length}<small> 개의 답변</small></div><div class="mini-bars">${[25,38,30,50,42,55,47,54].map(x=>`<i style="height:${x}px"></i>`).join("")}</div><small style="color:var(--muted)">이번 주 답변 참여가 이어지고 있어요</small></div></section><div class="section-head"><div><h2>공유 과목</h2><p>반과 수업 기간에 관계없이 모든 과목의 지식을 찾아보세요.</p></div><div class="search" style="max-width:300px"><input id="course-search" value="${esc(query)}" placeholder="과목 또는 교수자 검색"></div></div><section class="grid">${filtered.map(courseCard).join("")||`<div class="empty">검색 결과가 없어요.</div>`}</section><div class="section-head"><div><h2>지금 답변을 기다려요</h2><p>동료의 질문에 내가 아는 내용을 나눠보세요.</p></div><span class="badge open">${unanswered}개 질문</span></div><section class="feed">${data.questions.filter(q=>q.status==="OPEN").slice(0,3).map(questionCard).join("")}</section>`);
 document.querySelector("#course-search").oninput=e=>{query=e.target.value;coursesView()};
}
function courseCard(c){const [label,cls]=phase(c.phase);return `<a data-link href="/courses/${c.id}" class="course-card"><div class="course-top"><span class="course-icon ${c.color}">${c.code.split("-")[0]}</span><span class="badge ${cls}"><i class="dot"></i>${label}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><div class="course-meta"><span>${esc(c.instructors.join(" · "))}</span><span>${c.period}</span></div></a>`}
function questionCard(q){const a=author(q.authorId),count=answersFor(q.id).length;return `<a data-link href="/questions/${q.id}" class="question-card"><div><div class="q-meta">${statusBadge(q.status)}<span>${esc(a.name)} · ${a.classNumber||"교수자"}${a.classNumber?"반":""}</span><span>${date(q.createdAt)}</span></div><h3>${esc(q.title)}</h3><p>${esc(q.body.slice(0,100))}${q.body.length>100?"…":""}</p><div class="tags">${q.tags.map(t=>`<span class="tag"># ${esc(t)}</span>`).join("")}</div></div><div class="answer-count"><strong>${count}</strong>답변</div></a>`}

function courseView(id,tab=new URLSearchParams(location.search).get("tab")||"questions"){
 const c=course(id); if(!c)return go("/courses"); const qs=data.questions.filter(q=>q.courseId===c.id); const posts=data.posts.filter(p=>p.courseId===c.id); const materials=posts.filter(p=>p.type==="MATERIAL");
 let content="";
 if(tab==="questions") content=`<div class="toolbar"><div class="search"><input id="filter" placeholder="질문 제목과 내용을 검색하세요"></div><select class="select"><option>전체 상태</option><option>답변 대기</option><option>해결됨</option></select><button class="btn primary" data-go="/courses/${c.id}/questions/new">＋ 질문하기</button></div><div class="feed" id="question-feed">${qs.map(questionCard).join("")}</div>`;
 if(tab==="explanations") content=`<div class="section-head" style="margin-top:0"><div><h2>교수자 보충 설명</h2><p>수업에서 다 담지 못한 맥락을 다시 읽어보세요.</p></div></div><div class="feed">${posts.filter(p=>p.type==="EXPLANATION").map(p=>postCard(p)).join("")||`<div class="empty">아직 등록된 설명이 없어요.</div>`}</div>`;
 if(tab==="materials") content=`<div class="section-head" style="margin-top:0"><div><h2>학습자료</h2><p>최신 버전과 변경 내용을 먼저 확인하세요.</p></div></div><div class="feed">${materials.map(p=>postCard(p)).join("")}</div>`;
 app.innerHTML=shell(`${crumbs(c.title)}<section class="course-banner"><div><span class="badge ${phase(c.phase)[1]}">${phase(c.phase)[0]}</span><h1>${esc(c.title)}</h1><p>${esc(c.description)}</p></div><div class="banner-meta"><strong>담당 교수자</strong>${esc(c.instructors.join(" · "))}<br><br><strong>학습 기간</strong>${c.period}</div></section><nav class="tabs">${[["questions","질문과 답변",qs.length],["explanations","보충 설명",posts.filter(p=>p.type==="EXPLANATION").length],["materials","학습자료",materials.length]].map(x=>`<a data-link class="tab ${tab===x[0]?"active":""}" href="/courses/${c.id}?tab=${x[0]}">${x[1]} <small>${x[2]}</small></a>`).join("")}</nav><div class="layout"><section>${content}</section><aside class="sidebar"><div class="side-card"><h3>최근 자료 변경</h3>${materials.map(p=>{const seen=data.reads[`${user.id}:${p.id}`]||0,v=p.versions[0];return `<a data-link href="/posts/${p.id}" class="update"><b>${esc(p.title)}</b><small>v${v.number} · ${seen<v.number?"● 확인 필요":"확인함"}</small></a>`}).join("")}</div><div class="side-card"><h3>과목 한눈에 보기</h3><div class="course-meta"><span>열린 질문</span><b>${qs.filter(q=>q.status==="OPEN").length}</b></div><div class="course-meta"><span>전체 답변</span><b>${qs.reduce((n,q)=>n+answersFor(q.id).length,0)}</b></div></div></aside></div>`);
 const f=document.querySelector("#filter");if(f)f.oninput=e=>{document.querySelector("#question-feed").innerHTML=qs.filter(q=>(q.title+q.body).includes(e.target.value)).map(questionCard).join("")||`<div class="empty">찾는 질문이 없어요. 새 질문을 남겨보세요.</div>`};
}
function postCard(p){const u=author(p.authorId),v=p.versions?.[0],seen=v?(data.reads[`${user.id}:${p.id}`]||0)>=v.number:true;return `<a data-link href="/posts/${p.id}" class="question-card"><div><div class="q-meta"><span class="badge ${p.type==="MATERIAL"?"live":"prof"}">${p.type==="MATERIAL"?`자료 · v${v.number}`:"교수자 설명"}</span><span>${esc(u.name)} 교수자</span><span>${date(p.updatedAt)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p>${v?`<div class="tags"><span class="tag">${esc(v.fileName)}</span><span class="tag">${seen?"확인함":"● 새 버전"}</span></div>`:""}</div><div class="answer-count"><strong>›</strong>보기</div></a>`}

function questionView(id){const q=data.questions.find(x=>x.id===Number(id));if(!q)return go("/courses");const c=course(q.courseId),u=author(q.authorId);const ans=answersFor(q.id).sort((a,b)=>(b.roleAtCreation==="PROFESSOR")-(a.roleAtCreation==="PROFESSOR")||new Date(a.createdAt)-new Date(b.createdAt));app.innerHTML=shell(`<div class="detail">${crumbs(c.title,"질문 상세")}<article class="detail-head"><div style="display:flex;justify-content:space-between;gap:10px">${statusBadge(q.status)}${q.authorId===user.id?`<button class="btn secondary" id="resolve">${q.status==="OPEN"?"해결로 표시":"다시 열기"}</button>`:""}</div><h1>${esc(q.title)}</h1><div class="author-row"><span class="avatar">${esc(u.name[0])}</span><b>${esc(u.name)}</b><span>${u.classNumber}반 교육생</span><span>·</span><span>${date(q.createdAt)}</span></div><p class="detail-body">${esc(q.body)}</p><div class="tags">${q.tags.map(t=>`<span class="tag"># ${esc(t)}</span>`).join("")}</div></article><h2 class="answer-title">답변 ${ans.length}</h2>${ans.map(answerCard).join("")||`<div class="empty">첫 번째 답변을 남겨주세요.</div>`}<form class="answer composer card" id="answer-form"><b>답변 나누기</b><textarea name="body" rows="5" placeholder="알고 있는 내용이나 함께 살펴볼 관점을 적어주세요." required></textarea><div class="composer-actions"><span>서로의 학습에 도움이 되는 표현을 사용해주세요.</span><button class="btn primary">답변 등록</button></div></form></div>`);const res=document.querySelector("#resolve");if(res)res.onclick=async()=>{await api.toggleResolved(q.id);await refresh();toast(q.status==="OPEN"?"질문을 해결로 표시했어요.":"질문을 다시 열었어요.")};document.querySelector("#answer-form").onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector("button");b.disabled=true;await api.addAnswer(q.id,e.currentTarget.body.value.trim());await refresh();toast("답변이 등록됐어요.")}}
function answerCard(a){const u=author(a.authorId),prof=a.roleAtCreation==="PROFESSOR";return `<article class="answer ${prof?"professor":""}"><div class="author-row"><span class="avatar">${esc(u.name[0])}</span><b>${esc(u.name)}</b>${prof?`<span class="badge prof">교수자</span>`:`<span>${u.classNumber}반 교육생</span>`}<span>· ${date(a.createdAt)}</span></div><p>${esc(a.body)}</p></article>`}

function newQuestionView(courseId){const c=course(courseId);app.innerHTML=shell(`${crumbs(c.title,"새 질문")}<form class="form form-card" id="question-form"><h1>새 질문 작성</h1><p>질문은 모든 반에 공유됩니다. 상황과 시도한 내용을 구체적으로 적어주세요.</p><div class="field"><label>질문 제목</label><input name="title" maxlength="150" placeholder="무엇이 궁금한가요?" required><div class="hint">핵심이 드러나는 한 문장으로 적어주세요.</div></div><div class="field"><label>질문 내용</label><textarea name="body" maxlength="20000" placeholder="궁금한 점, 현재 상황, 이미 시도한 방법을 함께 적어주세요." required></textarea></div><div id="similar" class="similar-box hidden"></div><div class="form-actions"><button type="button" class="btn secondary" id="similar-btn">⌕ 유사 질문 확인</button><button type="button" class="btn ghost" data-go="/courses/${c.id}">취소</button><button class="btn primary">질문 등록</button></div></form>`);document.querySelector("#similar-btn").onclick=()=>{const title=document.querySelector('[name=title]').value;const tokens=title.split(/\s+/).filter(x=>x.length>1);const candidates=data.questions.filter(q=>q.courseId===c.id&&tokens.some(t=>q.title.includes(t))).slice(0,3);const box=document.querySelector("#similar");box.classList.remove("hidden");box.innerHTML=`<h3>비슷한 질문을 먼저 확인해보세요</h3>${candidates.length?candidates.map(q=>`<a data-link href="/questions/${q.id}" class="similar-item">${esc(q.title)} · 답변 ${answersFor(q.id).length}</a>`).join(""):`<div class="similar-item">비슷한 질문을 찾지 못했어요. 그대로 등록할 수 있어요.</div>`}`;bindGlobal()};document.querySelector("#question-form").onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector("button[type=submit]");btn.disabled=true;btn.textContent="등록 중…";const fields=e.currentTarget.elements;const q=await api.createQuestion({courseId:c.id,title:fields.namedItem("title").value.trim(),body:fields.namedItem("body").value.trim()});await refresh(false);toast("질문이 모든 반에 공유됐어요.");go(`/questions/${q.id}`)}}

function postView(id){const p=data.posts.find(x=>x.id===Number(id));if(!p)return go("/courses");const c=course(p.courseId),u=author(p.authorId);if(p.type==="EXPLANATION"){app.innerHTML=shell(`<div class="detail">${crumbs(c.title,"보충 설명")}<article class="detail-head"><span class="badge prof">교수자 보충 설명</span><h1>${esc(p.title)}</h1><div class="author-row"><span class="avatar">${u.name[0]}</span><b>${esc(u.name)} 교수자</b><span>· ${date(p.updatedAt)}</span></div><p class="detail-body">${esc(p.body)}</p><button class="btn secondary" data-go="/courses/${c.id}/questions/new">이 설명에서 질문하기 →</button></article></div>`);return}const latest=p.versions[0],seen=(data.reads[`${user.id}:${p.id}`]||0)>=latest.number;app.innerHTML=shell(`<div class="detail">${crumbs(c.title,"학습자료")}<article class="material-hero"><div style="display:flex;justify-content:space-between;gap:10px"><span class="badge live">최신 v${latest.number}</span><span class="badge ${seen?"resolved":"soon"}">${seen?"이 버전 확인함":"● 확인 필요"}</span></div><h1>${esc(p.title)}</h1><p class="detail-body">${esc(p.body)}</p><div class="file-panel"><div class="file-info"><span class="file-icon">${latest.fileName.split(".").pop().toUpperCase()}</span><span><b>${esc(latest.fileName)}</b><small>${latest.size} · 최신 버전</small></span></div><div style="display:flex;gap:8px"><button class="btn ghost" id="download">↓ 다운로드</button><button class="btn primary" id="read" ${seen?"disabled":""}>${seen?"확인 완료":"이 버전 확인"}</button></div></div><div class="similar-box" style="margin-top:18px"><b>v${latest.number} 변경 내용</b><p style="margin:7px 0 0;color:var(--muted)">${esc(latest.note)}</p></div></article><div class="section-head"><div><h2>버전 기록</h2><p>이전 자료와 변경 내용을 모두 확인할 수 있어요.</p></div></div><div class="card timeline">${p.versions.map(v=>`<div class="version"><h4>v${v.number} · ${esc(v.fileName)}</h4><p>${esc(v.note)} · ${v.size}</p></div>`).join("")}</div></div>`);document.querySelector("#download").onclick=()=>toast("초안에서는 실제 파일 다운로드를 제공하지 않아요.");document.querySelector("#read").onclick=async()=>{await api.markRead(p.id,latest.number);await refresh();toast("이 버전을 확인했어요.")}}

async function refresh(rerender=true){data=await api.snapshot();user=data.users.find(x=>x.id===data.sessionUserId)||null;if(rerender)render()}
async function render(){data=await api.snapshot();user=data.users.find(x=>x.id===data.sessionUserId)||null;const path=location.pathname;if(!user){loginView();return}if(path==="/"||path==="/login"){go("/courses");return}let m;if(path==="/courses")coursesView();else if((m=path.match(/^\/courses\/(\d+)\/questions\/new$/)))newQuestionView(m[1]);else if((m=path.match(/^\/courses\/(\d+)$/)))courseView(m[1]);else if((m=path.match(/^\/questions\/(\d+)$/)))questionView(m[1]);else if((m=path.match(/^\/posts\/(\d+)$/)))postView(m[1]);else coursesView();bindGlobal()}
function bindGlobal(){document.querySelectorAll("[data-link]").forEach(a=>a.onclick=e=>{e.preventDefault();go(a.getAttribute("href"))});document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));const out=document.querySelector("#logout");if(out)out.onclick=async()=>{await api.logout();go("/login")}}
addEventListener("popstate",render);render();
